### ISSUE TITLE
m3u8 Stream on Android

### ISSUE THREAD

**Issue by husmen73** [danielR2001/flutter_exoplayer#14]
Radio Stream URL: https://r3.rocketcdn.com/slowturk/abr/slowturk/256/chunks.m3u8

I'm getting this error after play button clicked.

This error occured also on your example app.

> I/ExoPlayerImpl(19182): Init 331b4222 [ExoPlayerLib/2.10.3] [generic_x86, Android SDK built for x86, unknown, 22]
> I/flutter (19182): PlayerState.BUFFERING
> E/ExoPlayerImplInternal(19182): Source error.
> E/ExoPlayerImplInternal(19182): com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor) could read the stream.
> E/ExoPlayerImplInternal(19182): 	at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractorHolder.selectExtractor(ProgressiveMediaPeriod.java:1059)
> E/ExoPlayerImplInternal(19182): 	at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:947)
> E/ExoPlayerImplInternal(19182): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
> E/ExoPlayerImplInternal(19182): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
> E/ExoPlayerImplInternal(19182): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
> E/ExoPlayerImplInternal(19182): 	at java.lang.Thread.run(Thread.java:818)
> I/flutter (19182): PlayerState.STOPPED

Tested on Android Simulator API 21
Tested on Huawei P20 Pro API 28

**Comment by danielR2001** [comment]
Hi, as you can see from the error the stream couldn't be read by the Exoplayer extractors. I can't fix it because the JAVA library isn't mine, but you could write an issue to them [ExoPlayer](https://github.com/google/ExoPlayer).

**Comment by husmen73** [comment]
Please check this repo https://github.com/siddhesh-tamhanekar/media_player

He is also using same library and m3u8 files are working. Your plugins notification system very good but he is not. At this moment Im using two plugin to solve my problem.

I know some Java but its not enough to make plugin now.

**Comment by danielR2001** [comment]
Ok, I will look at it as soon as possible.

**Comment by ripetrescu** [comment]
I remember implementing exoplayer using Android SDK (Kotlin) and had a similar problem. And I had to use HlsMediaSource for m3u8 streams (https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/source/hls/HlsMediaSource.Factory.html)

**Comment by ripetrescu** [comment]
Hi, any news on this? Thanks
