### ISSUE TITLE
example does not play

### ISSUE THREAD

**Issue by mohammadne** [danielR2001/flutter_exoplayer#20]
```
Init 71a6f1d [ExoPlayerLib/2.10.3] [generic_x86_arm, AOSP on IA Emulator, Google, 28]
I/flutter ( 7054): PlayerState.BUFFERING
E/ExoPlayerImplInternal( 7054): Source error.
E/ExoPlayerImplInternal( 7054): com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://dls.tabanmusic.com/music/1398/09/13/Reza-Bahram-Del-128.mp3
E/ExoPlayerImplInternal( 7054): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:287)
E/ExoPlayerImplInternal( 7054): 	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:257)
E/ExoPlayerImplInternal( 7054): 	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
E/ExoPlayerImplInternal( 7054): 	at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:934)
E/ExoPlayerImplInternal( 7054): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
E/ExoPlayerImplInternal( 7054): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal( 7054): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal( 7054): 	at java.lang.Thread.run(Thread.java:764)
E/ExoPlayerImplInternal( 7054): Caused by: java.io.IOException: Cleartext HTTP traffic to dls.tabanmusic.com not permitted
E/ExoPlayerImplInternal( 7054): 	at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:115)
E/ExoPlayerImplInternal( 7054): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:458)
E/ExoPlayerImplInternal( 7054): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
E/ExoPlayerImplInternal( 7054): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:556)
E/ExoPlayerImplInternal( 7054): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:443)
E/ExoPlayerImplInternal( 7054): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:285)
E/ExoPlayerImplInternal( 7054): 	... 7 more
I/flutter ( 7054): PlayerState.STOPPED
```

this is the error .

**Comment by danielR2001** [comment]
I think the mp3 stream is broken. try to use a different stream directory.

**Comment by mohammadne** [comment]
no the problem was for my emulater pixel 3,
I run the example with another emulater (one plus 6) and a real device (honor 10) and that was ok.
