### ISSUE TITLE
Work with other background isolate plugins

### ISSUE THREAD

**Issue by mohammadne** [danielR2001/flutter_exoplayer#22]
```
FATAL EXCEPTION: main
E/AndroidRuntime( 6079): Process: com.gerama, PID: 6079
E/AndroidRuntime( 6079): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.app.Activity.getApplicationContext()' on a null object reference
E/AndroidRuntime( 6079): 	at danielr2001.audioplayer.AudioPlayerPlugin.<init>(AudioPlayerPlugin.java:93)
E/AndroidRuntime( 6079): 	at danielr2001.audioplayer.AudioPlayerPlugin.registerWith(AudioPlayerPlugin.java:87)
E/AndroidRuntime( 6079): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:24)
E/AndroidRuntime( 6079): 	at com.gerama.MyApplication.registerWith(MyApplication.kt:15)
E/AndroidRuntime( 6079): 	at vn.hunghd.flutterdownloader.DownloadWorker.startBackgroundIsolate(DownloadWorker.java:124)
E/AndroidRuntime( 6079): 	at vn.hunghd.flutterdownloader.DownloadWorker.access$000(DownloadWorker.java:59)
E/AndroidRuntime( 6079): 	at vn.hunghd.flutterdownloader.DownloadWorker$1.run(DownloadWorker.java:97)
E/AndroidRuntime( 6079): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime( 6079): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 6079): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 6079): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime( 6079): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6079): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 6079): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime( 6079): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
I/Process ( 6079): Sending signal. PID: 6079 SIG: 9
Lost connection to device.
```
I am using flutter downloader and fireBaseMasseging

**Comment by mohammadne** [comment]
please answer quickly , I am in hurry .
Thanks

**Comment by mohammadne** [comment]
and when I want to play an audio :
```
Rejecting re-init on previously-failed class java.lang.Class<com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23>
I/art     ( 9813): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23>
I/art     ( 9813): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23>
I/art     ( 9813): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23>
I/art     ( 9813): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.exoplayer2.video.MediaCodecVideoRenderer$OnFrameRenderedListenerV23>
I/ExoPlayerImpl( 9813): Init 27af7034 [ExoPlayerLib/2.10.3] [A5010, A5010, OnePlus, 22]
E/ExoPlayerImplInternal( 9813): Source error.
E/ExoPlayerImplInternal( 9813): com.google.android.exoplayer2.upstream.FileDataSource$FileDataSourceException: java.io.FileNotFoundException: /data/data/com.gerama/app_flutter/Musics/780.mp3: open failed: ENOENT (No such file or directory)
E/ExoPlayerImplInternal( 9813): 	at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:73)
E/ExoPlayerImplInternal( 9813): 	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:257)
E/ExoPlayerImplInternal( 9813): 	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
E/ExoPlayerImplInternal( 9813): 	at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:934)
E/ExoPlayerImplInternal( 9813): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
E/ExoPlayerImplInternal( 9813): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/ExoPlayerImplInternal( 9813): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/ExoPlayerImplInternal( 9813): 	at java.lang.Thread.run(Thread.java:818)
E/ExoPlayerImplInternal( 9813): Caused by: java.io.FileNotFoundException: /data/data/com.gerama/app_flutter/Musics/780.mp3: open failed: ENOENT (No such file or directory)
E/ExoPlayerImplInternal( 9813): 	at libcore.io.IoBridge.open(IoBridge.java:456)
E/ExoPlayerImplInternal( 9813): 	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:117)
E/ExoPlayerImplInternal( 9813): 	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:149)
E/ExoPlayerImplInternal( 9813): 	at com.google.android.exoplayer2.upstream.FileDataSource.open(FileDataSource.java:65)
E/ExoPlayerImplInternal( 9813): 	... 7 more
E/ExoPlayerImplInternal( 9813): Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
E/ExoPlayerImplInternal( 9813): 	at libcore.io.Posix.open(Native Method)
E/ExoPlayerImplInternal( 9813): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
E/ExoPlayerImplInternal( 9813): 	at libcore.io.IoBridge.open(IoBridge.java:442)
E/ExoPlayerImplInternal( 9813): 	... 10 more
```

**Comment by danielR2001** [comment]
As I can see from the second issue the directory is just not valid: `Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)`

**Comment by danielR2001** [comment]
The first issue may be caused because of the other libraries, I will look at it tomorrow, and will try to come with a solution.

**Comment by mohammadne** [comment]
Also,  flutter downloader doesn't work

**Comment by danielR2001** [comment]
I've looked in the flutter downloader JAVA code and didn't find anything that could cause a conflict. I'm sorry.

**Comment by danielR2001** [comment]
I hope you will find the problem! :D

**Comment by tank777** [comment]
@mohammadne @danielR2001  For the first issue 
Have a look at fluttercommunity/flutter_downloader#145 and this [comment](https://github.com/fluttercommunity/flutter_downloader/issues/158#issuecomment-548248836)

**Comment by danielR2001** [comment]
Ok, I've looked at this comment but still didn't get the cause of the issue, is my plugin 
defined as UI? and I'm also registering my plugin with registerWith fun (JAVA).

**Comment by tank777** [comment]
@danielR2001  You don't need to do any changes in plugin. If we are using `FlutterDownloaderPlugin` or any other plugin which is used a background isolate and Application class in our project then we will need to register the plugin in application class. 

**i.e** 
```
public class DemoApplication extends FlutterApplication implements PluginRegistry.PluginRegistrantCallback {
    @Override
    public void registerWith(PluginRegistry registry) {
        FlutterDownloaderPlugin.registerWith(registry.registrarFor("vn.hunghd.flutterdownloader.FlutterDownloaderPlugin"));
    }
}
```
