### ISSUE TITLE
When I use flutter_exoplayer with flutter-downloader plugin will cause the application to crash directly

### ISSUE THREAD

**Issue by mrdong916** [danielR2001/flutter_exoplayer#25]
当我使用flutter_exoplayer与flutter-downloader插件一起使用时会导致应用直接闪退

When I use flutter_exoplayer with flutter-downloader plugin will cause the application to crash directly

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.app.Activity.getApplicationContext()' on a null object reference
	at danielr2001.audioplayer.AudioPlayerPlugin.<init>(AudioPlayerPlugin.java:93)
	at danielr2001.audioplayer.AudioPlayerPlugin.registerWith(AudioPlayerPlugin.java:87)
	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:33)
	at xyz.a5in.a5yin.MusicApplication.registerWith(MusicApplication.java:26)
	at vn.hunghd.flutterdownloader.DownloadWorker.startBackgroundIsolate(DownloadWorker.java:124)
	at vn.hunghd.flutterdownloader.DownloadWorker.access$000(DownloadWorker.java:59)
	at vn.hunghd.flutterdownloader.DownloadWorker$1.run(DownloadWorker.java:97)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:227)
	at android.app.ActivityThread.main(ActivityThread.java:7523)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)


```

**Comment by mrdong916** [comment]
另一个插件的同样原因造成的闪退，你可以参考下
Flashback caused by the same reason for another plugin, you can refer to

https://github.com/befovy/fijkplayer/issues/154

**Comment by tank777** [comment]
@mrdong916  could you please check #22? . May it will help.
https://github.com/danielR2001/flutter_exoplayer/issues/22#issuecomment-566021435

**Comment by mrdong916** [comment]
> @mrdong916 could you please check #22? . May it will help.
> [#22 (comment)](https://github.com/danielR2001/flutter_exoplayer/issues/22#issuecomment-566021435)

Thank you very much, I will try
