### ISSUE TITLE
Invalid Notification icon

### ISSUE THREAD

**Issue by emme10** [danielR2001/flutter_exoplayer#4]
Hello,

I tried to use your plugin to show a notification while playing audiofiles but the app crashes with the following stacktrace:

```
Couldn't find a unique registered media button receiver in the given context.
I/art     (10118): Do partial code cache collection, code=22KB, data=28KB
I/art     (10118): After code cache collection, code=20KB, data=27KB
I/art     (10118): Increasing code cache capacity to 128KB
I/ExoPlayerImpl(10118): Init e14189 [ExoPlayerLib/2.10.3] [hammerhead, Nexus 5, LGE, 25]
W/System  (10118): ClassLoader referenced unknown path: /system/framework/tcmclient.jar
I/flutter (10118): PlayerState.BUFFERING
W/VideoCapabilities(10118): Unrecognized profile 2130706433 for video/avc
I/VideoCapabilities(10118): Unsupported profile 4 for video/mp4v-es
W/AudioCapabilities(10118): Unsupported mime audio/ac3
W/AudioCapabilities(10118): Unsupported mime audio/alac
W/AudioCapabilities(10118): Unsupported mime audio/x-ape
W/AudioCapabilities(10118): Unsupported mime audio/ffmpeg
W/AudioCapabilities(10118): Unsupported mime audio/dts
W/AudioCapabilities(10118): Unsupported mime audio/mpeg-L2
W/AudioCapabilities(10118): Unsupported mime audio/vnd.rn-realaudio
W/AudioCapabilities(10118): Unsupported mime audio/x-ms-wma
W/VideoCapabilities(10118): Unsupported mime video/divx
W/VideoCapabilities(10118): Unsupported mime video/x-flv
W/VideoCapabilities(10118): Unsupported mime video/vnd.rn-realvideo
W/VideoCapabilities(10118): Unsupported mime video/vc1
W/VideoCapabilities(10118): Unsupported mime video/ffmpeg
W/VideoCapabilities(10118): Unsupported mime video/x-ms-wmv
E/ExoPlayerPlugin(10118): **Failed loading image!**
I/OMXClient(10118): MuxOMX ctor
I/ACodec  (10118): codec does not support config priority (err -2147483648)
D/AndroidRuntime(10118): Shutting down VM
I/flutter (10118): track changed to: 0
E/AndroidRuntime(10118): FATAL EXCEPTION: main
E/AndroidRuntime(10118): Process: myAppPackageName, PID: 10118
E/AndroidRuntime(10118): java.lang.IllegalArgumentException: **Invalid notification** (no valid small icon): Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x0 color=0x00000000 actions=3 vis=PRIVATE)
E/AndroidRuntime(10118): 	at android.app.NotificationManager.notifyAsUser(NotificationManager.java:313)
E/AndroidRuntime(10118): 	at android.app.NotificationManager.notify(NotificationManager.java:291)
E/AndroidRuntime(10118): 	at android.app.NotificationManager.notify(NotificationManager.java:275)
E/AndroidRuntime(10118): 	at danielr2001.audioplayer.notifications.MediaNotificationManager.showNotification(MediaNotificationManager.java:141)
E/AndroidRuntime(10118): 	at danielr2001.audioplayer.notifications.MediaNotificationManager.access$100(MediaNotificationManager.java:26)
E/AndroidRuntime(10118): 	at danielr2001.audioplayer.notifications.MediaNotificationManager$1.processFinish(MediaNotificationManager.java:213)
E/AndroidRuntime(10118): 	at danielr2001.audioplayer.notifications.LoadImageFromUrl.onPostExecute(LoadImageFromUrl.java:72)
E/AndroidRuntime(10118): 	at danielr2001.audioplayer.notifications.LoadImageFromUrl.onPostExecute(LoadImageFromUrl.java:19)
E/AndroidRuntime(10118): 	at android.os.AsyncTask.finish(AsyncTask.java:667)
E/AndroidRuntime(10118): 	at android.os.AsyncTask.-wrap1(AsyncTask.java)
E/AndroidRuntime(10118): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
E/AndroidRuntime(10118): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(10118): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(10118): 	at android.app.ActivityThread.main(ActivityThread.java:6186)
E/AndroidRuntime(10118): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10118): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
E/AndroidRuntime(10118): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
D/AudioTrack(10118): Client defaulted notificationFrames to 3675 for frameCount 11025
```

This is the AudioNotification like in your example:

```
final AudioNotification audioNotification = new AudioNotification(
    smallIconFileName: "ic_launcher",
    title: "audioTitle",
    subTitle: "artist1",
    largeIconUrl: 'graphics/testimage.png',
    isLocal: false,
    notificationActionMode: NotificationActionMode.ALL,
  );
```

audio is playing and was playing with the audioplaers plugin which is the base of this so there is only the problem with the notification itself.

**Comment by danielR2001** [comment]
Hi, Did you place your icon in the drawable folder?

**Comment by danielR2001** [comment]
"Attention! You need to place your app icon or the icon you want to show in the APP_NAME\android\app\src\main\res\drawable folder (you can drop multiple icons there), if you won`t do so your app will crash because android require a small icon for notification."

This is from my README.

**Comment by emme10** [comment]
Yes there is the the ic_launcher in the drawable folder that is generated by flutter itself.
I´ll try to place my own icon there tomorrow but I was sure it works with the standard flutter icon.

**Comment by danielR2001** [comment]
It's very strange, because my example uses also the flutter default icon. And also can you send all the code responsible for playing the audio.

**Comment by emme10** [comment]
Yes I know I double checked your example to spot any difference but nothing.

I get the Url from firebase and the audio is playing after the crash until I shut down the app completely so no issues there.
```
final Result result = await _audioPlayer.play(
        url,
        repeatMode: false,
        respectAudioFocus: true,
        playerMode: PlayerMode.FOREGROUND,
        audioNotification: audioNotification,
      );
```

**Comment by emme10** [comment]
Its working now. Somehow my icon was missing in the drawable folder. It was in the mipmap folders allthough I pasted it in the drawable folder. Strange but its working now so all good.
I hope to see an iOS Version of this awesome lib soon.
