### ISSUE TITLE
IllegalSeekPositionException

### ISSUE THREAD

**Issue by emme10** [danielR2001/flutter_exoplayer#7]
Since today this error occurs sometimes and the app crashes.
```

FATAL EXCEPTION: main
E/AndroidRuntime(11422): com.google.android.exoplayer2.IllegalSeekPositionException
E/AndroidRuntime(11422): 	at com.google.android.exoplayer2.ExoPlayerImpl.seekTo(ExoPlayerImpl.java:300)
E/AndroidRuntime(11422): 	at com.google.android.exoplayer2.SimpleExoPlayer.seekTo(SimpleExoPlayer.java:964)
E/AndroidRuntime(11422): 	at danielr2001.audioplayer.audioplayers.ForegroundAudioPlayer.initExoPlayer(ForegroundAudioPlayer.java:169)
E/AndroidRuntime(11422): 	at danielr2001.audioplayer.audioplayers.ForegroundAudioPlayer.playAll(ForegroundAudioPlayer.java:210)
E/AndroidRuntime(11422): 	at danielr2001.audioplayer.AudioPlayerPlugin$1.onServiceConnected(AudioPlayerPlugin.java:74)
E/AndroidRuntime(11422): 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1948)
E/AndroidRuntime(11422): 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1980)
E/AndroidRuntime(11422): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(11422): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(11422): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(11422): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime(11422): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11422): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(11422): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)


```

**Comment by danielR2001** [comment]
Hello, maybe you are passing starting index that isn't in the range of your playlist.
